# Selected Julia language features

There is a lot more than we can cover today.

The main take-aways are that Julia has all the features you would expect (and then some), it's straightforward to learn, and you can't start using it before you've learned everything.

## Variables

In [1]:
x = 1
y = 2
x + y

3

### Unicode and LaTeX variable names

In [2]:
# Korean
안녕하세요 = "Hello"

"Hello"

In [3]:
α = 1.0
β₁ = 2.0
β₂ = 3.0

α + β₁ * 5.0 + β₂ * 3.5

21.5

In [5]:
?π

"π" can be typed by \pi<tab>

search: π



```
π
pi
```

The constant pi.

# Examples

```jldoctest
julia> pi
π = 3.1415926535897...
```


In [4]:
π

π = 3.1415926535897...

### Even emojis

In [6]:
😺 = "Smiley cat"

"Smiley cat"

In [7]:
typeof(😺)

String

How could using emojis ever be a good idea?

#### Lotka–Volterra equations

A pair of first-order nonlinear differential equations used to describe the dynamics predators and their prey. See [Wikipedia](https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations).

Example taken from [DifferentialEquations.jl](https://diffeq.sciml.ai/stable/analysis/parameterized_functions/).

# Selected data structures

1. Tuples
2. Dictionaries
3. Arrays


### Tuples

In [1]:
my_favorite_languages = ("Julia", "Python", "R")

("Julia", "Python", "R")

In [2]:
my_favorite_languages[1]

"Julia"

Tuples are immutable, so it's an error to try this:

In [3]:
my_favorite_languages[3] = "Ruby"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

### Dictionaries

In [4]:
d1 = Dict(1 => 4.2, 2 => 5.3)

Dict{Int64, Float64} with 2 entries:
  2 => 5.3
  1 => 4.2

In [5]:
keys(d1)

KeySet for a Dict{Int64, Float64} with 2 entries. Keys:
  2
  1

In [6]:
values(d1)

ValueIterator for a Dict{Int64, Float64} with 2 entries. Values:
  5.3
  4.2

In [7]:
d1[2]

5.3

Keys and values can be arbitrary types.

In [8]:
d2 = Dict(1 => 4.2, :two => "hello") 

Dict{Any, Any} with 2 entries:
  :two => "hello"
  1    => 4.2

In [9]:
d2["whatever"] = true
d2

Dict{Any, Any} with 3 entries:
  "whatever" => true
  :two       => "hello"
  1          => 4.2

Or we can be explict about types.

In [10]:
d3 = Dict{Symbol, Int64}(:a => 1, :b => 2, :c => 3)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

Being explicit about types helps prevent certain kinds of bugs and also generally improves performance.

This will be an error because the types don't match.

In [11]:
d3["whatever"] = true

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Symbol
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:205
  Symbol(::String) at boot.jl:478
  Symbol(::AbstractString) at strings/basic.jl:228
  ...

### Arrays

Julia is designed for technical computing and it has extensive, first-class support for multi-dimensional arrays.

Indexing is 1-based.

In [12]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [13]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Vector{Any}:
 1
 1
 2
 3
  "Ted"
  "Robyn"

In [14]:
push!(fibonacci, 21);

In [15]:
fibonacci

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

In [16]:
pop!(fibonacci)

21

In [17]:
fibonacci

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

Assigment is by reference, so be careful.

In [18]:
somenumbers = fibonacci
somenumbers[3] = 999

999

In [19]:
fibonacci

7-element Vector{Int64}:
   1
   1
 999
   3
   5
   8
  13

To avoid this, use the ```copy``` function.

Multiple dimensional arrays are also supported.

In [20]:
rand(4, 3)

4×3 Matrix{Float64}:
 0.248046  0.443514  0.145132
 0.678724  0.12544   0.897306
 0.72742   0.427424  0.961196
 0.245867  0.706287  0.438904

In [21]:
rand(4, 2, 3)

4×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.298631  0.690561
 0.44997   0.395742
 0.649187  0.931462
 0.977279  0.0587381

[:, :, 2] =
 0.702809  0.625123
 0.045669  0.79958
 0.114157  0.688231
 0.707548  0.632306

[:, :, 3] =
 0.779742  0.612291
 0.415234  0.350598
 0.139392  0.487261
 0.285913  0.71455

# Control Flow

* Loops
* Array comprehensions

## Loops

### while loop

In [22]:
n = 0
while n < 5
    n += 1
    println(n)
end
n

1
2
3
4
5


5

### for loop

In [23]:
for n in 1:5
    println(n)
end

1
2
3
4
5


Let's create an addition table using some syntactic sugar for a nested for loop.

In [24]:
m, n = 5, 5
A = fill(0, (m, n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [25]:
for i in 1:m, j in 1:n
    A[i, j] = i + j
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## Array comprehensions

Here is the same thing in more idiomatic Julia using an *array comprehension*.

In [26]:
B = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10